# docker-compose.yml
version: '3'

services:
  serving:
    build:
      context: ./
      dockerfile: ./Dockerfile.serving
    image: ift6758
    ports:
      - 8000:8000
    environment:
      WANDB_API_KEY: 
#      args:
#        ARG: <ARG>
#    image: ift6758/serving:<TAG>
#    ports:
#      - <SERVING_PORT>:<SERVING_PORT>
#    environment:
#      DOCKER_ENV_VAR = ${LOCAL_ENV_VAR}
###### Uncomment below when you're ready to add the final notebook container to your docker compose
  streamlit:
    build:
      context: ./
      dockerfile: ./Dockerfile.streamlit
    image: ift6758/streamlit:latest
    ports:
      - 8501:8501

     
